config/routes.rb
Rails.application.routes.draw do

  get 'photos/filter', to: 'photos#filter', as: 'photos_filter'
  get 'photos/autocomplete', to: 'photos#autocomplete', as: 'photos_autocomplete'
  resources :photos
  get 'photos/post-gallery-ajax/:post', to: 'photos#post_gallery_ajax', as: 'photos_post_gallery_ajax'
  get 'photos/forpost/:post', to: 'photos#forpost', as: 'photos_for_post'
  get 'photos/popup/:photo', to: 'photos#popup', as: 'photo_popup'
  get 'photos/exif/:photo', to: 'photos#exif', as: 'photo_exif'
  post 'photos/sort/:post', to: 'photos#sort', as: 'photos_sort'

  get 'tags/for-:essence', to: 'tags#autocomplete', as: 'tags_autocomplete'
  get 'tags/filter', to: 'tags#filter', as: 'tags_filter'
  resources :tags

  get 'posts/filter', to: 'posts#filter', as: 'posts_filter'
  get 'posts/autocomplete', to: 'posts#autocomplete', as: 'posts_autocomplete'
  resources :posts

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'posts#index'

  get 'categories/delete/:id', to: 'categories#delete', as: 'category_delete'
  resources :categories

  resources :users
  resources :sessions

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  TYPE_POST = 'post'
  TYPE_PHOTO = 'photo'

  has_and_belongs_to_many :posts
  has_many :post_tag, class_name: PostTag

  has_and_belongs_to_many :photos
  has_many :photo_tag, class_name: PhotoTag


  #scope for post
  scope :search_by_tag, ->(q) {
    q = q.to_s.strip
    if (q.length > 0)
      where(["title like ?", "%#{q}%"])
    end
  }

  scope :from_post, -> { where('tags.for = ?', Tag::TYPE_POST) }
  scope :from_photo, -> { where('tags.for = ?', Tag::TYPE_PHOTO) }

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    get_tags_with_filter
  end

  def filter
    get_tags_with_filter
    render partial: 'table_content', formats: :html
  end


  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  def autocomplete
    term = params[:term]
    essence = params[:essence]
    max_count = !params[:max_count].blank? && params[:max_count].to_i > 1 ? params[:max_count].to_i : 10

    tags_criteria = Tag.limit(max_count)
    tags_criteria = essence == Tag::TYPE_POST ? tags_criteria.from_post : tags_criteria.from_photo

    if (term.empty?)
      @tags = tags_criteria.all
    else
      @tags = tags_criteria.search_by_tag(term).all
    end

    tags_titles = Array.new
    @tags.each do |tag|
      tags_titles.push(tag.title)
    end
    render :json => tags_titles
  end




  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:title, :count)
    end

  def get_tags_with_filter

    tags_record = Tag

    @sort = {
        :title => 'asc'
    }
    if (params[:sort].present?)
      @sort = params[:sort]
    end

    if (params[:filter].present?)
      #by name
      tags_record = tags_record.search_by_tag(params[:filter][:name])

      # by post
      if (params[:filter][:posts].present?)
        posts = params[:filter][:posts].split(',').uniq
        tags_record = tags_record.joins(:posts)
        tags_record = tags_record.where('posts.id IN (?)', posts)
      end

      # by photo
      if (params[:filter][:photos].present?)
        posts = params[:filter][:photos].split(',').uniq
        tags_record = tags_record.joins(:photos)
        tags_record = tags_record.where('photos.id IN (?)', photos)
      end

    end

    @sort.each do |column,direction|
      tags_record = tags_record.order(column.to_s + ' ' + direction.to_s)
    end

    # paging
    @per_page = 1
    if (cookies[:tags_per_page].present?)
      @per_page = cookies[:tags_per_page];
    end
    if (params[:per_page].present? && params[:per_page].to_i > 0)
      @per_page = params[:per_page].to_i;
    end
    cookies[:tags_per_page] = { :value => @per_page, :expires => 10.day.from_now }

    @tags = tags_record.paginate(:page => params[:page], :per_page => @per_page)
  end
  
end

app/views/tags/_filter.erb
<%
   now = Time.now.to_s
   filterInput = {};
   filterInput[:name] = params[:filter].present? ? params[:filter][:name] : ''
   filterInput[:posts] = params[:filter].present? ? params[:filter][:posts] : ''
   filterInput[:photos] = params[:filter].present? ? params[:filter][:photos] : ''
%>
<div><a class="to-toggle to-toggle-filter">Filter</a></div>
<div class="form-wrapper col-sm-5 toggle-filter" style="padding-top: 15px;<%if !params[:filter].present?%> display: none;<%end%>">
    <form class="form-horizontal" role="form" method="get" action="" id="post-filter-form">
      <div class="form-group">
        <label for="inputTitle" class="col-sm-3 control-label">Title</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="inputTitle" placeholder="title for search" name="filter[name]" value="<%=filterInput[:name]%>">
        </div>
      </div>

      <div class="form-group">
        <label for="inputPosts" class="col-sm-3 control-label">Posts</label>
        <div class="col-sm-9">
          <textarea class="tags-post-filter" name="filter[tags]" id="inputPosts">
            <%=filterInput[:posts]%>
          </textarea>
        </div>
      </div>

      <div class="form-group">
        <label for="inputPhotos" class="col-sm-3 control-label">Photos</label>
        <div class="col-sm-9">
          <textarea class="tags-photos-filter" name="filter[tags]" id="inputPhotos">
            <%=filterInput[:photos]%>
          </textarea>
        </div>
      </div>

      <div class="form-group">
        <label for="inputFor" class="col-sm-3 control-label">For</label>
        <div class="col-sm-9">
          <%= select_tag 'filter[for]', options_for_select(['photo', 'post'], filterInput[:for]), {:class => 'form-control', :id => 'inputFor'}%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-4">
          <button type="submit" class="btn btn-primary btn-lg" id="filter-post">Filter</button>
        </div>
      </div>
    </form>
</div>
<div class="clearfix"></div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_table_content.html.erb
<table class="table table-condensed">
  <thead>
  <tr>
    <th>
      <a href="#"
         data-by="id"
         data-direction="<%=@sort[:id].present? ? @sort[:id] : 'empty'%>"
         data-new-direction="<%if (!@sort[:id].present?)%>desc<%elsif @sort[:id] == 'asc'%>empty<%else%>asc<%end%>"
         class="change-sort"
      >
        <span>#</span>
        <span class="glyphicon <%if (!@sort[:id].present?)%>glyphicon-sort<%elsif @sort[:id] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>
    <th>
      <a href="#"
         data-by="title"
         data-direction="<%=@sort[:title].present? ? @sort[:title] : 'empty'%>"
         data-new-direction="<%if (!@sort[:title].present?)%>asc<%elsif @sort[:title] == 'desc'%>empty<%else%>desc<%end%>"
         class="change-sort"
      >
        <span>Title</span>
        <span class="glyphicon <%if (!@sort[:title].present?)%>glyphicon-sort<%elsif @sort[:title] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>
    <th>For</th>
    <th>
      <a href="#"
         data-by="count_photos"
         data-direction="<%=@sort[:count].present? ? @sort[:count] : 'empty'%>"
         data-new-direction="<%if (!@sort[:count].present?)%>desc<%elsif @sort[:count] == 'asc'%>empty<%else%>asc<%end%>"
         class="change-sort"
      >
        <span>Count</span>
        <span class="glyphicon <%if (!@sort[:count].present?)%>glyphicon-sort<%elsif @sort[:count] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>

    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @tags.each do |tag|%>
      <tr>
        <td><%= tag.id %></td>
        <td><%= tag.title %></td>
        <td><%= tag.for %></td>
        <td><%=tag.count%></td>
        <td>
          <%= link_to 'Show', tag,  { :class=>'btn btn-sm btn-info' } %>
          <%= link_to 'Edit', edit_tag_path(tag), { :class=>'btn btn-sm btn-success' } %>
          <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @tags, renderer: BootstrapPagination::Rails, :id => true %>
<div class="btn-group btn-group-per-page" role="group" data-per-page="<%=@per_page%>">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <%=@per_page%> items on page
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">1</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">10</a></li>
    <li><a href="#">100</a></li>
  </ul>
</div>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<%= link_to 'New Tag', new_tag_path, {:class => 'btn btn-primary'} %>

<%= render 'filter' %>
<div id="tags-content">
  <%= render 'table_content'%>
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tag.title %>
</p>

<p>
  <strong>Count:</strong>
  <%= @tag.count %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>