config/routes.rb
Rails.application.routes.draw do

  get 'photos/filter', to: 'photos#filter', as: 'photos_filter'
  get 'photos/autocomplete', to: 'photos#autocomplete', as: 'photos_autocomplete'
  resources :photos
  get 'photos/post-gallery-ajax/:post', to: 'photos#post_gallery_ajax', as: 'photos_post_gallery_ajax'
  get 'photos/forpost/:post', to: 'photos#forpost', as: 'photos_for_post'
  get 'photos/popup/:photo', to: 'photos#popup', as: 'photo_popup'
  get 'photos/exif/:photo', to: 'photos#exif', as: 'photo_exif'
  post 'photos/sort/:post', to: 'photos#sort', as: 'photos_sort'

  get 'tags/for-:essence', to: 'tags#autocomplete', as: 'tags_autocomplete'
  get 'tags/filter', to: 'tags#filter', as: 'tags_filter'
  resources :tags

  get 'posts/filter', to: 'posts#filter', as: 'posts_filter'
  get 'posts/autocomplete', to: 'posts#autocomplete', as: 'posts_autocomplete'
  resources :posts

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'posts#index'

  get 'categories/delete/:id', to: 'categories#delete', as: 'category_delete'
  resources :categories

  resources :users
  resources :sessions

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  RATING_MIN_500PX = 4
  STATUS_TO_NOT_PUBLISH = 0
  STATUS_TO_PUBLISH = 1
  STATUS_PUBLISHED = 2


 # has_and_belongs_to_many :posts
  has_many :post_photo, class_name: PostPhoto, dependent: :destroy
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :posts, :join_table => :posts_photos
  has_many :photo_tag, class_name: PhotoTag

  has_attached_file :image,
                    :styles => {
                        :blog => '2000x2000>',
                        :zoom => '1000x1000>',
                        :list => '300x300#',
                        :medium => '300x300>',
                        :thumb => '100x100>'
                    },
                    :convert_options => {
                        :blog => '-quality 100',
                        :zoom => '-quality 100',
                        :list => '-quality 100',
                        :medium => '-quality 100',
                        :thumb => '-quality 100',
                        :original => '-quality 100'
                    },
                    :default_url => '/images/:style/missing.png'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  before_create :set_title_before_save

  #scope for post
  scope :from_post, ->(postId) {
    postId = postId.to_i
    if (postId > 0)
      joins(:post_photo).
      where('posts_photos.post_id = ?', postId)
    end
  }

  #scope for photo title
  scope :by_name, ->(name) {
    if (name.length > 0)
      where('photos.title LIKE ?', "%#{name}%")
    end
  }

  #scope for sorting photos
  scope :sort_photos_asc, -> { order('sort ASC') }


  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
        'id' => self.id,
        'name' => read_attribute(:image_file_name),
        'size' => read_attribute(:image_file_size),
        'url' => image.url(:original),
        'thumbnail_url' => image.url(:thumb),
        'list_url' => image.url(:list),
        'delete_url' => photo_path(self),
        'update_url' => photo_popup_path(self),
        'delete_type' => 'DELETE'
    }
  end


  def image_file_size
    helper = Object.new.extend(ActionView::Helpers::NumberHelper)
    helper.number_to_human_size(read_attribute(:image_file_size))
  end


  private
  def set_title_before_save
    if (self.title.to_s.length < 1)
      stops = ['.jpeg', '.jpg']
      self.title = self.image_file_name.gsub(Regexp.union(stops), '')
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  def index
    get_photos_with_filter
  end

  def filter
    get_photos_with_filter
    @show_filter = true
    render partial: 'photo_list', formats: :html
  end

  def autocomplete
    term = params[:term]
    max_count = !params[:max_count].blank? && params[:max_count].to_i > 1 ? params[:max_count].to_i : 10

    photo_criteria = Photo.limit(max_count)

    if (term.empty?)
      photos = photo_criteria.all
    else
      photos = photo_criteria.by_name(term).all
    end

    photo_title_arr = Array.new
    photos.each do |photo|
      photo_title_arr.push(
          {
              :label => photo.title,
              :value => ApplicationHelper::Photo.post_autocomplete_title(post),
              :id => post.id
          }
      )
    end
    render :json => photo_title_arr
  end


  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  def forpost
    post_id = params[:post]
    if (!post_id)
      raise 'there is no post in in input params'
    end

    @photos = Photo.sort_photos_asc.from_post(post_id).all
    @post = Post.find(post_id)

    respond_to do |format|
      format.html
      format.json { render json: @photos.map{|photo| photo.to_jq_upload } }
    end
  end

  def post_gallery_ajax
    post_id = params[:post]
    if (!post_id)
      raise 'there is no post in in input params'
    end

    @photos = Photo.sort_photos_asc.from_post(post_id).all
    render partial: 'post_gallery_ajax', formats: :html
  end


  def popup
    photo_id = params[:photo]
    if (!photo_id)
      raise 'there is no post in in input params'
    end

    @photo = Photo.find(photo_id)
    @posts = Post.joins(:posts_photos).where('posts_photos.photo_id = ?', photo_id)

    @tags_arr = Array.new
    @post_arr = Array.new

    if (!@posts.empty?)
      tags = @photo.tags.any? ?  @photo.tags : @posts[0].tags
      tags.each do |tag|
        @tags_arr.push(tag.title)
      end

      @posts.each do |post|
        @post_arr.push(ApplicationHelper::Post.post_autocomplete_title(post))
      end
    end

    #default values
    @photo.geo_latitude = @photo.geo_latitude.present? ? @photo.geo_latitude : (@posts[0].present? ? @posts[0].geo_latitude : Rails.application.config.default_geo_latitude )
    @photo.geo_longitude = @photo.geo_longitude.present? ? @photo.geo_longitude : (@posts[0].present? ? @posts[0].geo_longitude : Rails.application.config.default_geo_longitude )
    @exif = ActiveSupport::JSON.decode(@photo.exif)
    render partial: 'popup', formats: :html
  end

  def exif
    photo_id = params[:photo]
    if (!photo_id)
      raise 'there is no post in in input params'
    end

    photo = Photo.find(photo_id)
    path = Rails.root + photo.image.path(:original)

    @exif_raw_hash = {}
    exifRaw = %x(identify -verbose #{path}).split("\n")
    exifRaw.each do |exifString|
      exif_arr = exifString.sub('exif:', '').strip.split(':').collect { |x| x.strip }
      #if (['Image', 'Format', 'Mime', 'Geometry', 'Resolution', 'Colorspace', 'Depth', 'Pixels', 'Quality', 'Orientation', 'DateTime', 'FocalLength', 'FocalLengthIn35mmFilm', 'Make', 'MaxApertureValue', 'Model', 'Software', 'Created Date[2,55]', 'Version'].include?(exif_arr[0]))
        @exif_raw_hash[exif_arr[0]] = exif_arr[1]
      #end
      #render :text => exif_arr
      #break
    end
  end

  # sort images
  def sort
    post_id = params[:post]
    sorted = params[:sorted].uniq

    # get ids from the DB
    existValues = Photo.where('`photos`.`id` IN (?)', sorted).from_post(post_id).select('photos.id').all.to_a
    # cj=heck by count
    if (existValues.length != sorted.length)
      raise 'error in images count'
    end
    #check by each id
    existValuesHash = {}
    existValues.each do |value|
     existValuesHash[value.id.to_i] = true
    end

    sorted.each do |value|
      value = value.to_i
      if (existValuesHash.has_key?(value))
        existValuesHash.delete(value)
      else
        raise "error photo id=#{value} does not exist in a post #{post_id}"
      end
    end


    if (existValuesHash.length > 0)
      raise 'not all the images from post set to be sorted'
    end

    # build the sql query
    sqlCode = "INSERT INTO `#{Photo.table_name}` (id,sort) VALUES"
    values = []
    sorted.each_with_index do |id, index|
      sort = (index+1)*100
      values.push "(#{id},#{sort})"
    end
    sqlCode += values.join(',').to_s + 'ON DUPLICATE KEY UPDATE sort=VALUES(sort);'

    ActiveRecord::Base.connection.execute(sqlCode)

    render :json => {success: true} and return
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end


  # POST /uploads
  # POST /uploads.json
  def create

    p_attr = params[:photo]
    p_attr.permit!
    @photo = Photo.new(p_attr)

    respond_to do |format|
      if @photo.save
        #save new link between photo and post
        if (params[:post_id].length)

          countInPost = PostPhoto.where(post_id: params[:post_id]).count
          @photo.sort = (countInPost+1)*100
          @photo.save

          #check post
          post = Post.find(params[:post_id])
          if (!post.present?)
            raise 'Post is not found'
          end

          if (post.main_photo.to_i < 1)
            post.main_photo = @photo.id
            post.save
          end

          post_photo = PostPhoto.find_or_initialize_by(post_id: params[:post_id], photo_id: @photo.id)
          post_photo.save

        end

        format.html {
          render :json => [@photo.to_jq_upload].to_json,
                 :content_type => 'text/html',
                 :layout => false
        }
        format.json { render json: {files: [@photo.to_jq_upload]}, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    # myParams = photo_params
    respond_to do |format|
      if @photo.update(photo_params)

        # save tags
        save_tags true

        PostPhoto.delete_all(photo_id: @photo.id)
        if (params[:posts].length > 0)
          posts = params[:posts].split(',').uniq
          posts.each do |post_id|
            post_photo = PostPhoto.find_or_initialize_by(post_id: post_id, photo_id: @photo.id)
            post_photo.save
          end
        end

        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json {
          render json: {
            status: :ok,
            photo: @photo
          }
        }
      else
        format.html { render :edit }
        format.json {
          render json: {
              errors => @photo.errors,
              status => :error
          },
          status: :unprocessable_entity
        }
      end
    end
  end


  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    #remove main photo if necessary
    post = Post.where(main_photo: @photo.id).first
    if (post.present?)
      first_photo = Photo.sort_photos_asc.from_post(post.id).first
      if (first_photo.present?)
        post.main_photo = firstPhoto.id
        post.save
      end
    end

    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_photos_with_filter
      photo_record = Photo

      #counts
      photo_record = photo_record.select('photos.*').joins('LEFT JOIN posts_photos ON posts_photos.photo_id = photos.id').joins('LEFT JOIN posts ON posts_photos.post_id = posts.id')

      if (params[:filter].present?)
        #by name
        photo_record = photo_record.by_name(params[:filter][:name])

        # by tags
        if (params[:filter].present? && params[:filter][:tags].present?)
          tags = params[:filter][:tags].split(',').uniq
          photo_record = photo_record.joins(:tags)
          photo_record = photo_record.where('tags.title IN (?)', tags)
        end

        # by dates
        if (params[:filter][:date_from].to_s.length > 0)
          photo_record = photo_record.where('posts.date_from >= ?',  DateTime.strptime(params[:filter][:date_from], '%d/%m/%Y'))
        end
        if (params[:filter][:date_to].to_s.length > 0)
          photo_record = photo_record.where('posts.date_to <= ?',  DateTime.strptime(params[:filter][:date_to], '%d/%m/%Y'))
        end
      end

      # paging
      @per_page = 4
      if (cookies[:photo_per_page].present?)
        @per_page = cookies[:photo_per_page];
      end
      if (params[:per_page].present? && params[:per_page].to_i > 0)
        @per_page = params[:per_page].to_i;
      end
      cookies[:photo_per_page] = { :value => @per_page, :expires => 10.day.from_now }

      # order_type
      @order_type = 'date'
      available_order_types = ['date', 'post']
      if (cookies[:photo_order_type].present? && (available_order_types.include? cookies[:photo_order_type]))
        @order_type = cookies[:photo_order_type];
      end
      if (params[:photo_order_type].present? && (available_order_types.include? cookies[:photo_order_type]))
        @order_type = params[:photo_order_type];
      end
      cookies[:photo_order_type] = { :value => @order_type, :expires => 10.day.from_now }

      if (@order_type == 'date')
        photo_record = photo_record.order('photos.created_at DESC')
      else
        photo_record = photo_record.order('posts.created_at DESC')
      end

      # get data
      @photos = photo_record.paginate(:page => params[:page], :per_page => @per_page)
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

app/helpers/photo_helper.rb
module PhotoHelper

  def self.focal_length(stringLength)
    stringLength = stringLength.to_s
    data = stringLength.split("/")
    if (data.length == 2)
      return (data[0].to_i / data[1].to_i).round
    else
      return stringLength
    end
  end
end

app/views/photos/_filter.erb
<%
   now = Time.now.to_s
   filterInput = {};
   filterInput[:name] = params[:filter].present? ? params[:filter][:name] : ''
   filterInput[:tags] = params[:filter].present? ? params[:filter][:tags] : ''
   filterInput[:dateFrom] = params[:filter].present? ? params[:filter][:date_from] : ''
   filterInput[:dateTo] = params[:filter].present? ? params[:filter][:date_to] : ''
%>
<div><a class="to-toggle to-toggle-filter">Filter</a></div>
<div class="form-wrapper col-sm-5 toggle-filter" style="padding-top: 15px;<%if !params[:filter].present?%> display: none;<%end%>">
    <form class="form-horizontal" role="form" method="get" action="" id="post-filter-form">
      <div class="form-group">
        <label for="inputTitle" class="col-sm-3 control-label">Title</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="inputTitle" placeholder="title for search" name="filter[name]" value="<%=filterInput[:name]%>">
        </div>
      </div>
      <div class="form-group">
        <label for="inputTags" class="col-sm-3 control-label">Tags</label>
        <div class="col-sm-9">
          <textarea class="post-tags-filter" name="filter[tags]" id="inputTags">
          <%=filterInput[:tags]%>
          </textarea>
        </div>
      </div>
      <div class="form-group">
        <label for="dateFrom" class="col-sm-3 control-label">Date from</label>
        <div class="col-sm-4">
          <input type="text" class="form-control datepicker" id="dateFrom" placeholder="" name="filter[date_from]" value="<%=filterInput[:dateFrom]%>">
        </div>
      </div>
      <div class="form-group">
        <label for="dateTo" class="col-sm-3 control-label">Date to</label>
        <div class="col-sm-4">
          <input type="text" class="form-control datepicker" id="dateTo" placeholder="" name="filter[date_to]" value="<%=filterInput[:dateTo]%>">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-4">
          <button type="submit" class="btn btn-primary btn-lg" id="filter-post">Filter</button>
        </div>
      </div>
    </form>
</div>
<div class="clearfix"></div>

app/views/photos/_form.html.erb
<div class="form-wrapper">
  <%= form_for(@photo, html: { class:'form-horizontal'}) do |f| %>



      <% if @photo.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <strong><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</strong>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :content, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%=f.text_area :content, :class => 'form-control' %>
      </div>
    </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Tags:</label>
        <div class="col-sm-10">
          <textarea class="photo-tags-editor" name="tags">
            <%=@tags_arr.join(',')%>
          </textarea>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Posts:</label>
        <div class="col-sm-10 col-posts">
          <textarea class="post-photo-filter" name="posts">
            <%=@post_arr.join(',')%>
          </textarea>
        </div>
      </div>

    <div class="form-group">
    <label class="col-sm-2 control-label">Map</label>
        <div class="col-sm-10">
          <fieldset class="gllpLatlonPicker">
            <input type="text" class="form-control gllpSearchField">
            <input type="button" class="btn btn-info gllpSearchButton" value="search">
            <input type="button" class="btn btn-info gllpSearchResize" value="resize">
            <div class="gllpMap" style="width: 800px">Google Maps</div>

            <%= f.hidden_field :geo_latitude, :class => 'gllpLatitude' %>
            <%= f.hidden_field :geo_longitude, :class => 'gllpLongitude' %>
            <input type="hidden" class="gllpZoom" value="4"/>
          </fieldset>
        </div>
    </div>

    <div class="alert alert-success alert-form-saved" role="alert" style="display: none">
        <strong>Well done!</strong> Data is updated
    </div>

    <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit :class => 'btn btn-success btn-lg' %>
        </div>
    </div>
  <% end %>
</div>
<script>
    var mapIsShown = false;
    function showMap(){
        if (mapIsShown === false) {
            mapIsShown = true;
            $(document).ready( function() {
                $("#block-<%=@photo.id%> .gllpLatlonPicker").each(function() {
                    (new GMapsLatLonPicker()).init( $(this) )
                });
            });
        }
    }

    $(function() {
        $('#block-<%=@photo.id%> .photo-tags-editor').tagEditor({
            autocomplete: {
                source: '/tags/for-photo',
                minLength: 2,
                delay: 0,
                position: { collision: 'flip' } }
        });

        $("#block-<%=@photo.id%> form").submit(function(e){
            e.preventDefault();
            var $this = $(this),
                $alertFormSaved = $this.find('.alert-form-saved'),
                $postAria = $('#block-<%=@photo.id%> .post-photo-filter'),
                postIdArr = [];

            $this.find('.post-id').each(function(value) {
                postIdArr.push($(this).text())
            });
            $postAria.val(postIdArr.join(','));

            $.ajax({
                url: $this.attr('action'),
                type: 'POST',
                dataType : 'json',
                data : $this.serialize(),
                success: function( data ) {
                    $alertFormSaved.show(function(){
                       setTimeout(function(){
                        $alertFormSaved.hide()
                       }, 2000);
                    });
                    console.log(data);
                },
                error: function( xhr, status, errorThrown ) {
                    alert( "Sorry, there was a problem!" );
                    console.log( "Error: " + errorThrown );
                    console.log( "Status: " + status );
                    console.dir( xhr );
                }
            });
        });

        $('#block-<%=@photo.id%> .post-photo-filter').tagEditor({
            //initialTags: ['tag1', 'tag2', 'tag3'],
            autocomplete: {
                source: '/posts/autocomplete',
                minLength: 2,
                delay: 0,
                forceLowercase : false,
                position: { collision: 'flip' }
            }
        });

    });


</script>

app/views/photos/_photo_list.html.erb
<div class="list-file-upload thumbnail-list thumbnail-list-<%= @view_type %>">
  <%
     i=0
     current_active_group = '';
     @photos.each do |photo|
       i+=1
       created_at_st = photo.created_at.strftime("%d %b. %Y")
       post_title_st = photo.posts[0].title

  %>
      <%if (
        (@order_type.present? && @order_type === 'date' && current_active_group != created_at_st) || (@order_type.present? && @order_type === 'post' && current_active_group != post_title_st)

      )
          i=1
          current_active_group = @order_type === 'date' ? created_at_st : post_title_st
      %>
          <div class="clearfix"></div>
          <div class="thumbnail-list__subtitle"><%=current_active_group%></div>
      <%end%>


      <div class="thumbnail" data-target="#modal-gallery" data-id="<%= photo.id %>">
        <a href="<%= photo_popup_path photo %>" class="photo-edit" role="button"><%= image_tag photo.image.url(:list), {:class => 'thumbnail__img'} %></a>

        <div class="thumbnail__caption">
          <input type="checkbox" name="photo[<%=photo.id%>]" value="1">
          <a href="<%= photo.image.url(:original) %>" title="<%= photo.image_file_name %>" class="thumbnail__image-title" download="<%= photo.image_file_name %>"><%= photo.title %></a>
          <div class="thumbnail__image-size"><%= photo.image_file_size %></div>
          <div class="thumbnail__posts">
            <% photo.posts.each do |post| %>
                <%= link_to post.title, posts_path({:post => post.title}), {:class => 'label label-primary'} %>
            <% end %>
          </div>
          <!--
              <div>
                  <strong>Tags:</strong>
                  <% photo.tags.each do |tag| %>
                      <%= link_to tag.title, posts_path({:tags => tag.title}), {:class => 'label label-primary'} %>
                  <% end %>
              </div>
              -->

          <div class="thumbnail__buttons">
            <div class="block-inline delete">
              <button class="btn btn-danger" data-type="DELETE" data-url="<%= photo_path(photo) %>">
                <i class="icon-trash icon-white"></i>
                <span><span class="glyphicon glyphicon-trash"></span> Delete</span>
              </button>
            </div>
            <a href="<%= photo_popup_path photo %>" class="block-inline btn btn-primary photo-edit" role="button"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
              Edit</a>
          </div>
        </div>
      </div>
      <% if (i%5 == 0) %>
          <div class="clearfix"></div>
      <% end %>
  <% end %>
</div>
<div class="clearfix"></div>
<% if ((defined?(locals[:show_filter]) && locals[:show_filter] == true) || (defined?(@show_filter) && @show_filter == true)) %>
    <%= will_paginate @photos, renderer: BootstrapPagination::Rails, :id => true %>
    <div class="btn-group btn-group-per-page" role="group" data-per-page="<%= @per_page %>">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <%= @per_page %> items on page
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><a href="#">4</a></li>
        <li><a href="#">8</a></li>
        <li><a href="#">16</a></li>
        <li><a href="#">32</a></li>
        <li><a href="#">256</a></li>
      </ul>
    </div>
<% end %>

app/views/photos/_popup_info.html.erb
<div class="form-wrapper">
    <h4 id="info-title"><%=@photo.title%></h4>

    <dl class="dl-horizontal">

      <dt id="info-id">Id:</dt>
      <dd><%=@photo.id%></dd>

      <dt id="info-post">Posts:</dt>
      <dd>
        <%@posts.each do |post|%>
            <%= link_to ApplicationHelper::Post.post_public_title(post), edit_post_path(post), {:class=>'label label-danger'}%>
        <%end%>
      </dd>

      <dt id="info-content">Content:</dt>
      <dd><%=@photo.content%></dd>

      <dt id="info-tag">Tags:</dt>
      <dd>
        <%@tags_arr.each do |tag|%>
            <%= link_to tag, photos_path({:tags => tag}), {:class=>'label label-primary'}%>
        <%end%>
      </dd>

      <dt id="info-exif">Exif:</dt>
      <dd>
        <%if @exif.any?%>
            <%if @exif['mime_type'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Mime type</span> <%=@exif['mime_type']%></div><%end%>
            <%if @exif['color_space'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Colorspace</span> <%=@exif['color_space']%></div><%end%>
            <%if @exif['resolution'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Resolution</span> <%=@exif['resolution']%></div><%end%>
            <%if @exif['file_size'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Size</span> <%=@exif['file_size']%></div><%end%>
            <%if @exif['image_size'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Image size</span> <%=@exif['image_size']%></div><%end%>
            <%if @exif['quality'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Quality</span> <%=@exif['quality']%></div><%end%>
            <%if @exif['camera'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Camera</span> <%=@exif['camera']%></div><%end%>
            <%if @exif['lens'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Lens</span> <%=@exif['lens']%></div><%end%>
            <%if @exif['focal_length'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Focal length</span> <%=@exif['focal_length']%></div><%end%>
            <%if @exif['scale_factor'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Scale factor</span> <%= @exif['scale_factor']%></div><%end%>
            <%if @exif['iso'].present?%><div class="col-md-5 padding-0"><span class="label label-success">ISO</span> <%=@exif['iso']%></div><%end%>
            <%if @exif['exposure_time'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Exposure time</span> <%=@exif['exposure_time']%></div><%end%>
            <%if @exif['aperture'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Aperture</span> <%=@exif['aperture']%></div><%end%>
            <%if @exif['modification_date'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Processed</span> <%=@exif['modification_date']%></div><%end%>
            <%if @exif['access_date'].present?%><div class="col-md-5 padding-0"><span class="label label-success">Exif checked</span> <%= @exif['access_date']%></div><%end%>
        <%end%>
      </dd>

      <dt id="info-map">Map:</dt>
      <dd>
        <%if(!@photo.geo_latitude.to_s.empty? && !@photo.geo_longitude.to_s.empty?) %>
            <img src="<%=UrlBuilding::ExternalUrlBuilder.static_map_url(@photo.geo_latitude,@photo.geo_longitude, 7, '640x320')%>" alt="Manhattan Normal Map" class="photo-static-map">
        <%end%>
      </dd>
    </dl>
</div>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/exif.html.erb
<%=debug(@exif_raw_hash)%>

app/views/photos/index.html.erb
<h1>All Photos</h1>
<%= render 'filter' %>
<div id="photo-content">
    <%= render 'photo_list', locals: { :show_filter => true} %>
</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>


<p>
  <strong>Width:</strong>
  <%= @photo.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @photo.height %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>