config/routes.rb
Rails.application.routes.draw do

  get 'photos/filter', to: 'photos#filter', as: 'photos_filter'
  get 'photos/autocomplete', to: 'photos#autocomplete', as: 'photos_autocomplete'
  resources :photos
  get 'photos/post-gallery-ajax/:post', to: 'photos#post_gallery_ajax', as: 'photos_post_gallery_ajax'
  get 'photos/forpost/:post', to: 'photos#forpost', as: 'photos_for_post'
  get 'photos/popup/:photo', to: 'photos#popup', as: 'photo_popup'
  get 'photos/exif/:photo', to: 'photos#exif', as: 'photo_exif'
  post 'photos/sort/:post', to: 'photos#sort', as: 'photos_sort'

  get 'tags/for-:essence', to: 'tags#autocomplete', as: 'tags_autocomplete'
  get 'tags/filter', to: 'tags#filter', as: 'tags_filter'
  resources :tags

  get 'posts/filter', to: 'posts#filter', as: 'posts_filter'
  get 'posts/autocomplete', to: 'posts#autocomplete', as: 'posts_autocomplete'
  resources :posts

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'posts#index'

  get 'categories/delete/:id', to: 'categories#delete', as: 'category_delete'
  resources :categories

  resources :users
  resources :sessions

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :photos
  has_many :post_tag, class_name: PostTag
  has_many :posts_photos, class_name: PostPhoto
  has_many :categories_posts, class_name: CategoryPost

  #scope for post
  scope :by_name, ->(name) {
    if (name.length > 0)
      where('posts.title LIKE ?', "%#{name}%")
    end
  }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    get_posts_with_filter
  end

  def filter
    get_posts_with_filter
    render partial: 'table_content', formats: :html
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @tags_arr = Array.new
    @post.tags.each do |tag|
      @tags_arr.push(tag.title)
    end

    @category_active_ids = Array.new
    @post.categories_posts.each do |cat_post|
      @category_active_ids.push(cat_post.category_id)
    end

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save

        save_tags false
        save_categories false

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    # myParams = post_params
    # render :text => myParams
    respond_to do |format|
      if @post.update(post_params)

        # save tags
        save_tags true
        save_categories true

        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def autocomplete
    term = params[:term]
    max_count = !params[:max_count].blank? && params[:max_count].to_i > 1 ? params[:max_count].to_i : 10

    post_criteria = Post.limit(max_count)

    if (term.empty?)
      posts = post_criteria.all
    else
      posts = post_criteria.by_name(term).all
    end

    post_title_arr = Array.new
    posts.each do |post|
      post_title_arr.push(
          {
              :label => post.title,
              :value => ApplicationHelper::Post.post_autocomplete_title(post),
              :id => post.id
          }
      )
    end
    render :json => post_title_arr
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      postParams = params.require(:post).permit(:title, :content, :date_from, :date_to, :filter, :geo_latitude, :geo_longitude)
      postParams[:date_from] = postParams[:date_from].to_s.length > 0 ? DateTime.strptime(postParams[:date_from], '%d/%m/%Y') : nil
      postParams[:date_to] = postParams[:date_to].to_s.length > 0 ? DateTime.strptime(postParams[:date_to], '%d/%m/%Y') : nil
      return postParams
    end

    # save tags in create and update post
    def save_tags(delete_old_tags = true)
      #delete all old tags
      if (delete_old_tags)
        PostTag.delete_all(post_id: @post.id)
      end
      #save new tags
      if (params[:tags].length > 0)
        tags = params[:tags].split(',').uniq
        tags.each do |tag_name|
          tag_name = tag_name.downcase.strip
          tag = Tag.find_or_initialize_by(title: tag_name, for: Tag::TYPE_POST)
          if (tag.save)
            #save linked table
            postTag = PostTag.create(post_id: @post.id, tag_id: tag.id)
            postTag.save
          end
        end
      end
    end


    def save_categories(delete_old_categories = true)
      #delete all old tags
      if (delete_old_categories)
        CategoryPost.delete_all(post_id: @post.id)
      end
      #save new categories
      if (params[:category].present? && params[:category].length > 0)
        params[:category].keys.each do |cat_id|
          category = Category.find(cat_id)
          if (!category)
            raise "Category #{cat_id} is not found"
          end
          #save linked table
          category.path_ids.each do |path_cat_id|
            categoryPost = CategoryPost.find_or_initialize_by(post_id: @post.id, category_id: path_cat_id)
            if (!categoryPost.save)
              raise "CategoryPost is not saved"
            end
          end
        end
      end
    end


    def get_posts_with_filter

      post_record = Post

      @sort = {
          :date_from => 'desc'
      }
      if (params[:sort].present?)
        @sort = params[:sort]
      end

      #counts
      post_record = post_record.select('posts.*, count(posts_photos.photo_id) as count_photos').joins('LEFT JOIN posts_photos ON posts_photos.post_id = posts.id').group('posts.id')

      if (params[:filter].present?)
        #by name
        post_record = post_record.by_name(params[:filter][:name])

        # by tags
        if (params[:filter][:tags].present?)
          tags = params[:filter][:tags].split(',').uniq
          post_record = post_record.joins(:tags)
          post_record = post_record.where('tags.title IN (?)', tags)
        end

        # by category
        if (params[:filter][:category].present?)
          post_record = post_record.joins(:categories_posts)
          post_record = post_record.where('categories_posts.category_id = ?', params[:filter][:category])
        end

        # by dates
        if (params[:filter][:date_from].to_s.length > 0)
          post_record = post_record.where('posts.date_from >= ?',  DateTime.strptime(params[:filter][:date_from], '%d/%m/%Y'))
        end
        if (params[:filter][:date_to].to_s.length > 0)
          post_record = post_record.where('posts.date_to <= ?',  DateTime.strptime(params[:filter][:date_to], '%d/%m/%Y'))
        end
      end

      @sort.each do |column,direction|
        post_record = post_record.order(column.to_s + ' ' + direction.to_s)
      end

      # paging
      @per_page = 1
      if (cookies[:per_page].present?)
        @per_page = cookies[:per_page];
      end
      if (params[:per_page].present? && params[:per_page].to_i > 0)
        @per_page = params[:per_page].to_i;
      end
      cookies[:per_page] = { :value => @per_page, :expires => 10.day.from_now }

      @posts = post_record.paginate(:page => params[:page], :per_page => @per_page)
    end
end

app/views/posts/_filter.erb
<%
   now = Time.now.to_s
   filterInput = {};
   filterInput[:name] = params[:filter].present? ? params[:filter][:name] : ''
   filterInput[:tags] = params[:filter].present? ? params[:filter][:tags] : ''
   filterInput[:dateFrom] = params[:filter].present? ? params[:filter][:date_from] : ''
   filterInput[:dateTo] = params[:filter].present? ? params[:filter][:date_to] : ''
%>
<div><a class="to-toggle to-toggle-filter">Filter</a></div>
<div class="form-wrapper col-sm-5 toggle-filter" style="padding-top: 15px;<%if !params[:filter].present?%> display: none;<%end%>">
    <form class="form-horizontal" role="form" method="get" action="" id="post-filter-form">
      <div class="form-group">
        <label for="inputTitle" class="col-sm-3 control-label">Title</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="inputTitle" placeholder="title for search" name="filter[name]" value="<%=filterInput[:name]%>">
        </div>
      </div>
      <div class="form-group">
        <label for="inputCategory" class="col-sm-3 control-label">Category</label>
        <div class="col-sm-9">
          <%= select_tag 'filter[category]', options_for_select(category_dropdown_options, filterInput[:category]), {:class => 'form-control'}%>
        </div>
      </div>
      <div class="form-group">
        <label for="inputTags" class="col-sm-3 control-label">Tags</label>
        <div class="col-sm-9">
          <textarea class="post-tags-filter" name="filter[tags]" id="inputTags">
          <%=filterInput[:tags]%>
          </textarea>
        </div>
      </div>
      <div class="form-group">
        <label for="dateFrom" class="col-sm-3 control-label">Date from</label>
        <div class="col-sm-4">
          <input type="text" class="form-control datepicker" id="dateFrom" placeholder="" name="filter[date_from]" value="<%=filterInput[:dateFrom]%>">
        </div>
      </div>
      <div class="form-group">
        <label for="dateTo" class="col-sm-3 control-label">Date to</label>
        <div class="col-sm-4">
          <input type="text" class="form-control datepicker" id="dateTo" placeholder="" name="filter[date_to]" value="<%=filterInput[:dateTo]%>">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-4">
          <button type="submit" class="btn btn-primary btn-lg" id="filter-post">Filter</button>
        </div>
      </div>
    </form>
</div>
<div class="clearfix"></div>

app/views/posts/_form.html.erb
<%
   @post.date_from =  @post.date_from.to_s.length > 0 ? @post.date_from.strftime('%d/%m/%Y') : ''
   @post.date_to = @post.date_to.to_s.length > 0 ? @post.date_to.strftime('%d/%m/%Y') : ''
   @post.geo_latitude = @post.geo_latitude.present? ? @post.geo_latitude : 20
   @post.geo_longitude = @post.geo_longitude.present? ? @post.geo_longitude : 20
   @tags_arr = @tags_arr.to_a.length > 0 ? @tags_arr : []
   @category_active_ids = @category_active_ids.to_a.length > 0 ? @category_active_ids : []
%>
<div class="form-wrapper">
    <%= form_for(@post, html: { class:'form-horizontal'}) do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <strong><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</strong>
          <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :content, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%=f.text_area :content, :class => 'tinymce' %>
          <%=tinymce%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Dates:</label>
        <div class="col-sm-10">
          <table>
            <tr>
              <td><%= f.label :date_from %>&nbsp;&nbsp;</td>
              <td><%= f.text_field :date_from, :class => 'form-control datepicker' %></td>
              <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
              <td><%= f.label :date_to %>&nbsp;&nbsp;</td>
              <td><%= f.text_field :date_to, :class => 'form-control datepicker' %></td>
            </tr>
          </table>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Tags:</label>
        <div class="col-sm-10">
          <textarea class="post-tags-editor" name="tags">
            <%=@tags_arr.join(',')%>
          </textarea>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Map:</label>
        <div class="col-sm-10">
          <fieldset class="gllpLatlonPicker">
            <input type="text" class="form-control gllpSearchField">
            <input type="button" class="btn btn-info gllpSearchButton" value="search">
            <div class="gllpMap" style="width:500px; height:500px;">Google Maps</div>

            <%= f.hidden_field :geo_latitude, :class => 'gllpLatitude' %>
            <%= f.hidden_field :geo_longitude, :class => 'gllpLongitude' %>
            <input type="hidden" class="gllpZoom" value="4"/>
          </fieldset>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Categories:</label>
        <div class="col-sm-10">

          <%CategoriesHelper::category_tree.each do |category|%>
            <div class="category-level category-level-<%=category[:level]%>">
              <input type="checkbox" name="category[<%=category[:id]%>]" id="category-id-<%=category[:id]%>"<%if (@category_active_ids.include?(category[:id])) %> checked="checked" <%end%>>
              <label for="category-id-<%=category[:id]%>"><%=category[:title]%></label>
            </div>
          <%end%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label"></div>
        <div class="col-sm-10">
          <%= f.submit :class => 'btn btn-success btn-lg' %>
        </div>
      </div>
    <% end %>
</div>

app/views/posts/_table_content.html.erb
<table class="table table-condensed">
  <thead>
  <tr>
    <th>
      <a href="#"
        data-by="id"
        data-direction="<%=@sort[:id].present? ? @sort[:id] : 'empty'%>"
        data-new-direction="<%if (!@sort[:id].present?)%>desc<%elsif @sort[:id] == 'asc'%>empty<%else%>asc<%end%>"
        class="change-sort"
      >
          <span>#</span>
          <span class="glyphicon <%if (!@sort[:id].present?)%>glyphicon-sort<%elsif @sort[:id] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>
    <th>
      <a href="#"
         data-by="title"
         data-direction="<%=@sort[:title].present? ? @sort[:title] : 'empty'%>"
         data-new-direction="<%if (!@sort[:title].present?)%>asc<%elsif @sort[:title] == 'desc'%>empty<%else%>desc<%end%>"
         class="change-sort"
      >
          <span>Title</span>
          <span class="glyphicon <%if (!@sort[:title].present?)%>glyphicon-sort<%elsif @sort[:title] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>
    <th>Tags</th>
    <th>
      <a href="#"
         data-by="count_photos"
         data-direction="<%=@sort[:count_photos].present? ? @sort[:count_photos] : 'empty'%>"
         data-new-direction="<%if (!@sort[:count_photos].present?)%>desc<%elsif @sort[:count_photos] == 'asc'%>empty<%else%>asc<%end%>"
         class="change-sort"
      >
          <span>Count</span>
          <span class="glyphicon <%if (!@sort[:count_photos].present?)%>glyphicon-sort<%elsif @sort[:count_photos] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>
    <th>
      <a href="#"
         data-by="date_from"
         data-direction="<%=@sort[:date_from].present? ? @sort[:date_from] : 'empty'%>"
         data-new-direction="<%if (!@sort[:date_from].present?)%>desc<%elsif @sort[:date_from] == 'asc'%>empty<%else%>asc<%end%>"
         class="change-sort"
      >
        <span>Dates</span>
        <span class="glyphicon <%if (!@sort[:date_from].present?)%>glyphicon-sort<%elsif @sort[:date_from] == 'asc'%>glyphicon glyphicon-sort-by-alphabet<%else%>glyphicon glyphicon-sort-by-alphabet-alt<%end%>" aria-hidden="true"></span>
      </a>
    </th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post|
    date_from =  post.date_from.to_s.length > 0 ? post.date_from.strftime('%d/%m/%Y') : 'not set'
    date_to = post.date_to.to_s.length > 0 ? post.date_to.strftime('%d/%m/%Y') : 'not set'
  %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td>
          <%post.tags.each do |tag|%>
              <%= link_to tag.title, posts_path({:tags => tag.title}), {:class=>'label label-primary'}%>
          <%end%>
        </td>
        <td><%=post.count_photos%></td>
        <td><%=date_from%>&nbsp;&mdash;&nbsp;<%=date_to%></td>
        <td>
          <%= link_to 'Show', post,  { :class=>'btn btn-sm btn-info' } %>
          <%= link_to 'Edit', edit_post_path(post), { :class=>'btn btn-sm btn-success' } %>
          <%= link_to 'Photos', photos_for_post_path({:post=>post.id}), { :class=>'btn btn-sm btn-primary' } %>
          <%#<button type="button" class="btn btn-sm btn-primary btn-show-photos" data-post="<%=post.id">Photos</button>%>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %>
          <%= (post.count_photos > 0) ? (link_to 'Show photos', photos_post_gallery_ajax_path({:post=>post.id}),  { :class=>'btn btn-sm btn-info btn-show-photos-ajax', :data => {:post_id => post.id}  }) : '' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails, :id => true %>
<div class="btn-group btn-group-per-page" role="group" data-per-page="<%=@per_page%>">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <%=@per_page%> items on page
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">1</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">10</a></li>
    <li><a href="#">100</a></li>
  </ul>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="page-header">All posts</h1>
<%= link_to 'New Post', new_post_path, {:class => 'btn btn-primary'} %>
<%= render 'filter' %>
<div id="table-content">
  <%= render 'table_content'%>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>