config/routes.rb
Rails.application.routes.draw do

  get 'photos/filter', to: 'photos#filter', as: 'photos_filter'
  get 'photos/autocomplete', to: 'photos#autocomplete', as: 'photos_autocomplete'
  resources :photos
  get 'photos/post-gallery-ajax/:post', to: 'photos#post_gallery_ajax', as: 'photos_post_gallery_ajax'
  get 'photos/forpost/:post', to: 'photos#forpost', as: 'photos_for_post'
  get 'photos/popup/:photo', to: 'photos#popup', as: 'photo_popup'
  get 'photos/exif/:photo', to: 'photos#exif', as: 'photo_exif'
  post 'photos/sort/:post', to: 'photos#sort', as: 'photos_sort'

  get 'tags/for-:essence', to: 'tags#autocomplete', as: 'tags_autocomplete'
  get 'tags/filter', to: 'tags#filter', as: 'tags_filter'
  resources :tags

  get 'posts/filter', to: 'posts#filter', as: 'posts_filter'
  get 'posts/autocomplete', to: 'posts#autocomplete', as: 'posts_autocomplete'
  resources :posts

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => 'posts#index'

  get 'categories/delete/:id', to: 'categories#delete', as: 'category_delete'
  resources :categories

  resources :users
  resources :sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotosLoc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=false' %>
</head>
<body>
<!-- Fixed navbar -->

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Photo archive</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left nav-section-menu" style="margin-left: 30px">
        <%if active_page('photos')%>
            <li class="show-view-type<%if (@view_type == 'grid')%> active<%end%>" data-type="grid"><a href="#"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> GRID</a></li>
            <li class="show-view-type<%if (@view_type == 'list')%>active<%end%>" data-type="list"><a href="#"><span class="glyphicon glyphicon glyphicon-th-list" aria-hidden="true"></span> LIST</a></li>
            <%if active_page('photos', 'index')%>
                <li class="show-order-type<%if (@order_type == 'date')%> active<%end%>" data-type="date"><a href="#"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Order by date</a></li>
                <li class="show-order-type<%if (@order_type == 'post')%> active<%end%>" data-type="post"><a href="#"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span> Order by post</a></li>
            <%end%>
        <%end%>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

<div class="container-fluid main-content">
  <div class="row">
    <div class="sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <li<%if active_page('categories')%> class="active"<%end%>><a href="<%=categories_path%>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Categories</a></li>
        <li<%if active_page('posts')%> class="active"<%end%>><a href="<%=posts_path%>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Posts</a></li>
        <li<%if active_page('photos')%> class="active"<%end%>><a href="<%=photos_path%>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Photos</a></li>
        <li<%if active_page('tags')%> class="active"<%end%>><a href="<%=tags_path%>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Tags</a></li>
        <li<%if active_page('configuration')%> class="active"<%end%>><a href="<%=categories_path%>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>configuration</a></li>
      </ul>
    </div>
    <div class="main main-block-<%=@layout_type%>">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :class => name == 'notice' ? 'alert alert-success' : 'alert alert-danger' %>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

<div class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myLargeModalLabel">Title</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>
</body>
</html>